name: "🐞 Сбой в системе"
description: "Сообщи об ошибке, баге или подозрительном поведении."
title: "[Сбой] "
labels: ["bug", "system-glitch"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Перед отправкой проверь**, не сообщал ли кто-то о подобном.
        Твоя ошибка — это важный сбой в симуляции.

  - type: textarea
    id: what-happened
    attributes:
      label: "Что произошло?"
      description: "Опиши суть бага или ошибки, что ожидалось, и что получилось."
      placeholder: |
        Пример: при переходе на уровень 2 появляется сбой анимации...
        value: ""
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Как воспроизвести?"
      description: "Перечисли шаги, как получить сбой."
      placeholder: |
        1. Открыть...
        2. Перейти...
        3. Нажать...
        4. Увидеть...
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: "Насколько критично?"
      options:
        - 🟢 Незначительно (можно жить)
        - 🟡 Средне (мешает, но можно обойти)
        - 🔴 Критично (всё ломает)
